version: '3'

services:
# Mongo DB service
  mongoDB:
    container_name: db_container
    image: mongo:latest
    ports:
      - 8081:8081
    volumes:
      - mongoDB:/data/db
    
# Node api service
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
       PORT : 3000
       MONGODB_URI : mongodb+srv://admin:admin@cluster0.l1ulkio.mongodb.net/
       DB_NAME : dockerize
    depends_on:
      - mongoDB
volumes:
  mongoDB: